### PR TITLE
Rework all routing to use named routes, plus refactoring and removal of redundant code

### PR DESCRIPTION
**Pull request by jongilbraith**
Right, this is a big PR.  Ordinarily I wouldn't dream of submitting something like this but this is no ordinary codebase.

The original goal was simply (not really simple) to go through all the url generation and make everything use named routes, as without doing that we wouldn't be able to set the ``RAILS_RELATIVE_URL_ROOT`` environment variable and have rails generate it's urls with a prefix, needed for the migration.

As I went through the routes I kept hitting redundant functionality (signup, comment previews, sidebar customisation, and so on) so I ended up just ripping a lot of that stuff out rather than updating it.

Additionally there was also tons of unnecessarily convoluted code to implement functionality we simply didn't need, such as the ability to customise the url format, which meant a large portion of route generation was being done in the model. So that all came out and we're left with something simple and predictable.

Then there were countless controllers which were structured like you'd find around the Rails 1.2 era, so I did a lot of breaking out of large multifunction methods (``if request.post?``, etc) into a separate, more restful kinds of structure.

I'm not really expecting anyone to review this. It's going to be subject to a thorough manual QA (the truth of the matter is, there's not that large amount of functionality to test). My plan then is over the next few months to continue to strip away a few more major areas of unneeded functionality after which I'll then start looking at improving test coverage and bringing the remaining code up to current standards.

I've labelled this PR WIP as I'm still going through the broken specs, but wanted to get some eyeballs on it sooner rather than later so this doesn't hold things up any more than it already has.

### CODE REVIEW

**Comment by jongilbraith** [comment]
@Tr4pSt3R @tomas-stefano

**Comment by Tr4pSt3R** [comment]
@jongilbraith try running: ```bundle exec rspec ./spec/controllers/tags_controller_spec.rb```

**Comment by jongilbraith** [comment]
@Tr4pSt3R what am I looking at? (Other than a broken spec, as I'd expect as I'm still working on the specs 😊)

**Comment by Tr4pSt3R** [comment]
@jongilbraith oh in that case add a [WIP] to the PR title if this is still work in progress?

**Comment by jongilbraith** [comment]
@Tr4pSt3R changed.

Also sounds like you've not read the PR's intro (which mentions the broken specs), which would be helpful for you to understand where I'm coming from before you delve deeper.

**Comment by Tr4pSt3R** [comment]
@jongilbraith nope, I didn't read the PR note sorry. But yeah I will continue looking through it

**Comment by tomas-stefano** [comment]
After fix the CI and squash the commits, this is good to go. :+1:

**Comment by jongilbraith** [comment]
Right, specs are passing now but not on CI, though @darokel's handover document says that's expected.

Just pulling in a fresh dump from production and starting a thorough smoke test.

QA tomorrow.

**Comment by tomas-stefano** [comment]
:+1: :+1:

**Comment by jongilbraith** [comment]
@tomas-stefano :+1: https://github.com/moneyadviceservice/publify/commit/203b41a436bc97b2edea444ff0205f08149c2426

**Comment by Tr4pSt3R** [comment]
:+1:

**Pull request merged**
