### PR TITLE
[DEV APPROVED] Adding brightcove video snippet to blog

### PR DESCRIPTION
**Pull request by johnplayer1982**
Adding Brightcove video snippet, using same width + height as the default youtube video embed code to add consistency

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
@johnplayer1982 any chance of a visual? What does it look like please? :) :)

**Comment by johnplayer1982** [comment]
No problem:

youtube-brightcove

**Comment by davidtrussler** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:100: :+1:

**Pull request merged**
