### PR TITLE
[DEV APPROVED] Adding survive January tag

### PR DESCRIPTION
**Pull request by johnplayer1982**
Updating seed.db to include the tag "Survive January" for the upcoming campaign.  The tag has already been added to staging and signed off, and is also now on production.

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
:100: :+1:

**Comment by darokel** [comment]
This is a seeds file and only ran once when the app was first deployed. You'll need to either manually add the tag in the Heroku DB or re-seed this file once it's merged.

**Comment by Tr4pSt3R** [comment]
yes, I concur with what David said!

**Comment by darokel** [comment]
Leave the tag in the seeds file anyway so it's added whenever initial data needs to be seeded. Then I think you'll be better off to go into Heroku Rails console and run `Tag.create(name: tag, display_name: tag.gsub(/-/, " ").titleize)` swapping out `tag` for your tag name.

**Comment by johnplayer1982** [comment]
Thanks @darokel The tag update has been through staging and production, I'll update the PR with more info

**Comment by darokel** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1: :+1:

**Pull request merged**
