### PR TITLE
[DEV APPROVED] Update Readme for eventmachine :notebook:

### PR DESCRIPTION
**Pull request by jriga**
**Note**
Update note on how to install gem `eventmachine`

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
👍 👍

**Comment by jongilbraith** [comment]
👍 

Though I'm also asking myself what the hell publify could need eventmachine for.....

**Comment by jongilbraith** [comment]
Ah I see, it's through the guard dependency. Would be inclined to just ditch guard and avoid the problem altogether myself.

**Comment by tomas-stefano** [comment]
Sounds good to remove guard 👍

**Comment by jriga** [comment]
♻️

**Comment by jongilbraith** [comment]
Niiiiice. 👍

**Pull request merged**
