### PR TITLE
Adding search to the blog

### PR DESCRIPTION
**Pull request by Guntrisoft**
- re-enabled the search magnify button in top right
- adjusted padding in header to match main MAS site
  as per request by Jade
- modified search results page to include
  search box and format search results to match
  archive page

### CODE REVIEW

**Comment by Guntrisoft** [comment]
@benbarnett @jongilbraith

**Comment by jongilbraith** [comment]
Have sorted the page title for when there's no search query.

It's a bit hacky but right now I haven't got time for anything better.

**Comment by jongilbraith** [comment]
:+1: for the rest.

**Comment by Guntrisoft** [comment]
@benbarnett if you could just give this the once over then i'll merge it

**Comment by benbarnett** [comment]
:+1:

**Pull request merged**
