### PR TITLE
[DEV APPROVED] 7473 remove alt text from the campaign hero image

### PR DESCRIPTION
**Pull request by jongilbraith**
Despite the fact that the campaigns have a field for the hero image alt text, it would appear that we were never using it and so the image_tag helper was just inferring an alt text from the filename.

I've added a null alt text as specified in the ticket, removed the alt text from the campaign interface, and removed the attribute from the model entirely.

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
👍

**Comment by slaywell** [comment]
👍

**Comment by andyhl** [comment]
QA 👍

**Comment by jongilbraith** [comment]
Awesome, cheers @andyhl. Shall merge now then.

**Pull request merged**
