### PR TITLE
Add optimizely script to blog

### PR DESCRIPTION
**Pull request by jonalport**

### CODE REVIEW

**Comment by benbarnett** [comment]
Tres nice :+1:

**Comment by darokel** [comment]
Could you move the file to `vendor/javascripts`?

**Comment by jonalport** [comment]
@darokel - have moved to partial which @asmega approved of

Measured improvement using the inline script as opposed to blocking tag.

**Comment by asmega** [comment]
:+1:

**Comment by jonalport** [comment]
Ok I've changed it back to the simplest method, referencing the file on optimizely's server. The performance is not bad, and the file is now smaller as we have moved the blog specific tests into a new project.

**Pull request merged**
