### PR TITLE
Prep for Rackspace migration

### PR DESCRIPTION
**Pull request by darokel**
Small PR to:

- Create build and test scripts needed to deploy the blog via Go
- Configure `database.yml.mysql` to match db config in puppet

Waiting on https://github.com/moneyadviceservice/scripts/pull/300

### CODE REVIEW

**Comment by jongilbraith** [comment]
@tomas-stefano @Tr4pSt3R Just need thumbs for @darokel's changes when you get a sec :-)

**Comment by tomas-stefano** [comment]
LGTM :+1:

**Comment by Tr4pSt3R** [comment]
All good good 
@darokel && @jongilbraith

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by darokel** [comment]
@jongilbraith Damn that's a lot of commits! :fire:

**Comment by jongilbraith** [comment]
@darokel haha, and they're all big'uns too!

**Pull request merged**
