### PR TITLE
Reference root in path to icons

### PR DESCRIPTION
**Pull request by Guntrisoft**
- I was finding that the favicon wasn't working on articles
  because it was referencing something in the 'current directory'
  which was causing a 404
- Added name of blog as application name for Windows 8

### CODE REVIEW

**Comment by Guntrisoft** [comment]
@baphled @benbarnett

**Comment by Guntrisoft** [comment]
@baphled is /url-of-image.png the right path anyway? - seems to work ok on localhost

**Comment by benbarnett** [comment]
:+1:

**Comment by baphled** [comment]
@Guntrisoft looks good to me. Strange though, I could of sworn I added a leading `/` before committing o_0

**Comment by baphled** [comment]
:+1:

**Pull request merged**
