### PR TITLE
Rebrand the MAS blog to MoneyHelper

### PR DESCRIPTION
**Pull request by johnplayer1982**
Please see the [Figma](https://www.figma.com/file/Mmh2IPhVyol3IIpZ3f1BWW/321---Digital-Style-Guidelines?node-id=11766%3A7113) for how this should look.

This PR includes the rebranding of the following elements:

**- Header**

image

**- Footer and footer links section**

image

**- Homepage and Tags page panels**

image

**- Tags title**

image

**- Search form and results**

image

**- Author meta info**

image

**- Comment form and user comments**

image

**- "You might also like" section on article pages**

image

**- Listed tags on the article page (in the hero section)**

image

**- inline callout**

image

**- 'MA says' callout**

image

** - Link style, default, hover, focus, visited **

image

Apologies it's massive, and that I've done it 😆

### CODE REVIEW

**Review by davidtrussler — APPROVED** [review]
LGTM! 👍

**Comment by davidtrussler** [comment]
Hello @andreferreiradlw, did you have any comments on this PR? I was considering proceeding with a deploy to test otherwise.

**Review by andreferreiradlw — APPROVED** [review]

**Comment by johnplayer1982** [comment]
@davidtrussler @andreferreiradlw is this good to go to test?

**Comment by davidtrussler** [comment]
> @davidtrussler @andreferreiradlw is this good to go to test?

@johnplayer1982 Yeah, sorry, I said I'd do that but other stuff took over. I'll get back to it later today.

**Comment by davidtrussler** [comment]
> > @davidtrussler @andreferreiradlw is this good to go to test?
> 
> @johnplayer1982 Yeah, sorry, I said I'd do that but other stuff took over. I'll get back to it later today.

Hmm, this is failing quite a few RSpec tests so can't really be deployed as it is. Most of them seem to already be present in the master branch rather than being introduced in this work but they will need to be assigned to be fixed before deploying. See [here](http://az4-svc-bld04.dev.mas.local:8080/job/publify/job/moneyhelper-rebrand/) for failures on Jenkins. @johnplayer1982 @andreferreiradlw

**Pull request closed without merging**
