### PR TITLE
Xml sitemap

### PR DESCRIPTION
**Pull request by asmega**
- Tweak existing sitemap to only return url to resources and remove other content
- Add news sitemap which returns only news articles within the last 48 hours. This contains specific content for google news

### CODE REVIEW

**Comment by benbarnett** [comment]
:+1:

**Comment by jonalport** [comment]
:+1:

**Comment by asmega** [comment]
- I've removed a duplicate gem in the Gemfile which was throwing a warning
- There was also a requirement change. The normal sitemap no longer includes new articles

**Comment by rnalexander** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by tomas-stefano** [comment]
:+1:

**Pull request merged**
